### ISSUE TITLE
Sail above VT

### ISSUE THREAD

**Issue by ilyaigpetrov** [runabove/sail#12]
Hi, I have CPU without VT.
Docker works until it faces VT:

```sh-session
>docker login --username=ilyaigpetrov --password=... --email=... sailabove.io
An error occurred trying to connect: Post http://localhost:2375/v1.21/auth: dial tcp 127.0.0.1:2375: ConnectEx tcp: No connection could be made because the target machine actively refused it.
```

Can I use sailabove without VT?
With `sail` tool only?
Please, let me know if runabove still offer free vm instances I can use.

**Comment by yadutaf** [comment]
Hi @ilyaigpetrov,

VT instructions are for virtual machines. The ``docker`` command you are using to login on Sailabove is an HTTP client, connecting to the docker daemon on you machine. The error displayed above suggests that the docker daemon is simply not running or not listening on port 2375.

**Comment by ilyaigpetrov** [comment]
@yadutaf Thank you for your reply.
My processor doesn't support VT instruction set, which is required by docker on non-linux platforms (Windows in my case). Docker daemon is ran inside vm in Windows with help of this VT.

Anyway, I've switched to linux and everything works fine now.

It would be cool if you could reduce data transfers from: _hub > local > sailabove.io_  -- to direct:  _hub > sailabove_.

Thanks.

**Comment by yadutaf** [comment]
Glad to know it's working now. Thanks for your feedback. I'll forward your suggestion to the team. This sounds like a great idea.
