### ISSUE TITLE
method not allowed

### ISSUE THREAD

**Issue by sdieunidou** [runabove/sail#13]
Bonjour,

Pas sur que ce soit le bon dépot pour cela ; mais lorsque j'essaie de push une image docker l'API ovh semble bloquer :

```
$ docker push sailabove.io/yatooprint/samuelebistoletti/docker-statsd-influxdb-grafana
The push refers to a repository [sailabove.io/yatooprint/samuelebistoletti/docker-statsd-influxdb-grafana] (len: 1)
Sending image list
Error: Status 405 trying to push repository yatooprint/samuelebistoletti/docker-statsd-influxdb-grafana: "\"Method not allowed.\""
```

**Comment by yadutaf** [comment]
Le noms des images docker sont de la forme: ``<registry>/<account>/<name>``. Dans le cas de l'image que vous poussez, il y a une 4ème composant dans le nom de l'image qui cause cette erreur.

**Comment by sdieunidou** [comment]
Merci pour ce retour :)
