### ISSUE TITLE
Problems with go 1.5

### ISSUE THREAD

**Issue by waja** [runabove/sail#6]
Hi,

I'm trying to create a Debian package of your application. I'm getting the following error:

```sh
$ dh-make-golang github.com/runabove/sail
2015/10/25 17:53:59 Downloading "github.com/runabove/sail/..."
go get: 109.99 MiBpackage github.com/runabove/sail/vendor/github.com/inconshreveable/go-update
	imports github.com/inconshreveable/go-update/internal/binarydist: use of internal package not allowed
package github.com/runabove/sail/vendor/github.com/inconshreveable/go-update
	imports github.com/inconshreveable/go-update/internal/osext: use of internal package not allowed
2015/10/25 17:55:01 Could not create a tarball of the upstream source: exit status 1
```

It seems it's related to the go version installed. It DOESN'T work on a system with:

```sh
$ dpkg -l | grep golang-go
ii  golang-go                        2:1.5.1-1                    i386         Go programming language compiler, linker, compiled stdlib
```

It works:

```sh
$ dpkg -l | grep golang-go
ii  golang-go                      2:1.3.3-1                   i386         Go programming language compiler
```

Crawling at google reveals, it may have something todo with:

https://golang.org/cmd/go/#hdr-Internal_Directories
https://golang.org/s/go14internal

Thanks for looking into this, Jan.

**Comment by yadutaf** [comment]
``sail`` makes use of the experimental vendoring feature introduced in golang 1.5. Can you make sure to ``export GO15VENDOREXPERIMENT=1`` in the build process to enable vendoring ?

You'll find build instructions in the "Hacking" section of the readme (https://github.com/runabove/sail#hacking). ``.travis.yml`` (https://github.com/runabove/sail/blob/master/.travis.yml) may contain valuable examples too.

Does it help ?

**Comment by waja** [comment]
Ah ... that was a good point and the one who reads your https://github.com/runabove/sail/blob/master/README.md#hacking will be not surprised. Anyways .. looks like there are many unpackaged dependencies in Debian missing.
So it seems not worse to package and maintain them all when you are providing a statical build binary which also works fine. :-)
